# Generated by Django 3.2.12 on 2022-03-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('repeats', models.SmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False, editable=False)),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.telegramgroup')),
            ],
        ),
    ]
