# Generated by Django 3.2.12 on 2022-03-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_user_contacts_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts_processed',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
