# Generated by Django 3.2.12 on 2022-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_contact_source_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='proccessed_by',
            field=models.ManyToManyField(to='tgbot.User'),
        ),
    ]
