# Generated by Django 3.2.12 on 2022-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_contact_proccessed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['repeats']},
        ),
        migrations.AddField(
            model_name='contact',
            name='failed_repeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='repeats',
            field=models.IntegerField(default=0),
        ),
    ]
