# Generated by Django 3.2.12 on 2022-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_auto_20220305_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts_processed_num',
        ),
        migrations.AddField(
            model_name='user',
            name='success_num',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
